FROM golang:1.23

RUN apt-get update -qq && \
    apt-get install -y -qq --no-install-recommends \
        libayatana-appindicator3-dev libgtk-3-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /src
